# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='City')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32, verbose_name='First name')),
                ('last_name', models.CharField(max_length=32, verbose_name='Last name')),
                ('middle_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Middle name')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('document_scan', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Country')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('client_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Client')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=256, verbose_name='Hotel')),
                ('hotel_star', models.IntegerField(default=1)),
                ('hotel_status', models.BooleanField()),
                ('hotel_children_under_tree', models.BooleanField()),
                ('hotel_pets_available', models.BooleanField()),
                ('hotel_description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('B', 'Booked'), ('PP', 'Partially Paid'), ('FP', 'Fully Paid')], max_length=1)),
                ('tour_count', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order_total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order_client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crm.Client')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=32, null=True, verbose_name='Phone')),
                ('client_phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Client')),
            ],
            options={
                'verbose_name': 'Phone',
                'verbose_name_plural': 'Phones',
            },
        ),
        migrations.CreateModel(
            name='PlusOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32, verbose_name='First name')),
                ('last_name', models.CharField(max_length=32, verbose_name='Last name')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('document_scan', models.ImageField(blank=True, null=True, upload_to='')),
                ('client_plus_one', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crm.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='Tour')),
                ('tour_start_date', models.DateField()),
                ('tour_end_date', models.DateField()),
                ('tour_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tour_nmb', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('city', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='crm.City')),
            ],
            options={
                'verbose_name': 'Tour',
                'verbose_name_plural': 'Tours',
            },
        ),
        migrations.CreateModel(
            name='TourSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(blank=True, max_length=64, null=True)),
                ('season_coefficient', models.IntegerField(default=1)),
                ('season_in_tour', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crm.Tour')),
            ],
        ),
        migrations.AddField(
            model_name='plusone',
            name='plus_one_in_tour',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crm.Tour'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_tour',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crm.Tour'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_in_tour',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crm.Tour'),
        ),
        migrations.AddField(
            model_name='country',
            name='country_in_tour',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crm.Tour'),
        ),
        migrations.AddField(
            model_name='client',
            name='client_tour',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crm.Tour'),
        ),
    ]
