# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20171004_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='client_phone',
        ),
        migrations.RemoveField(
            model_name='email',
            name='email',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='email',
            name='client_email',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='crm.Client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phone',
            name='client_phone',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='crm.Client'),
            preserve_default=False,
        ),
    ]
