# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 08:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20171008_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='tour_nmb',
        ),
    ]
