# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20171005_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='phone',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Phone'),
        ),
    ]
