# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_hotel_hotel_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourseason',
            name='season_in_tour',
        ),
        migrations.AddField(
            model_name='tour',
            name='season',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='crm.TourSeason'),
        ),
        migrations.AddField(
            model_name='tourseason',
            name='season_date',
            field=models.DateField(default=None),
        ),
    ]
