# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20171008_0820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourseason',
            old_name='season_date',
            new_name='season_end_date',
        ),
        migrations.AddField(
            model_name='tourseason',
            name='season_start_date',
            field=models.DateField(default=None),
        ),
    ]
