# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20171008_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_tour',
        ),
        migrations.RemoveField(
            model_name='email',
            name='client_email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_client',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_tour',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='client_phone',
        ),
        migrations.RemoveField(
            model_name='plusone',
            name='client_plus_one',
        ),
        migrations.RemoveField(
            model_name='plusone',
            name='plus_one_in_tour',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='city',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='country',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='season',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
        migrations.DeleteModel(
            name='PlusOne',
        ),
        migrations.DeleteModel(
            name='Tour',
        ),
        migrations.DeleteModel(
            name='TourSeason',
        ),
    ]
