# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tour', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentOrderTourist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='order_tourist_doc/')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('B', 'Booked'), ('PP', 'Partially Paid'), ('FP', 'Fully Paid')], max_length=2)),
                ('count', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order_total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='client.Client')),
                ('tour', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tour.Tour')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderTourist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32, verbose_name='First name')),
                ('last_name', models.CharField(max_length=32, verbose_name='Last name')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('document_scan', models.ImageField(blank=True, null=True, upload_to='')),
                ('client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='client.Client')),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
        ),
        migrations.AddField(
            model_name='documentordertourist',
            name='order_tourist',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.OrderTourist'),
        ),
    ]
